### ISSUE TITLE
Problems with internet explorer

### ISSUE THREAD

**Issue by Ices-Eyes** [Boemska/h54s#97]
Hi all,
glad to see the release of the v2 version of the lib. I have had some minor trouble updating (mostly date no more auto-formatted when sent back to the browser fom SAS), but now anything seems to work... Anything except internet explorer... It seems that the widely used let has some problem with it. Since SAS 9.4 SAS Portal (at least on M1) and Web report studio works good only with IE, is there any chance that h54s cold come back working with it too? :)

(or at least I think it is a let problem, the page stop with a console error of SCRIPT1006: Previsto ')' on ajax.js (5,1) )

**Comment by boemska-nik** [comment]
Hey @Ices-Eyes, yes it is that - it's down to us using ES6 variable declaration syntax. We might be able to do something with babel but it'll need testing, I'm not sure that's the _only_ thing that doesn't work on IE. What version of IE are you using? (please don't say ie8)

@cj13579 I wouldn't say it's a bug as it's expected behaviour, but I also wouldn't say that it's a wontfix. We can try and see if we can make it work. Might have to look for a polyfill for promise too.

**Comment by Ices-Eyes** [comment]
Nope not ie8... Ie7 😅
Just joking, we are on ie11 (win10). If only portal and wrs would work well with other browser I would bring all our user to use something else... But unfortunatly mainly wrs has big issues with other browsers :(

**Comment by boemska-nik** [comment]
Ok thanks. I just realised browserstack actually lets us test all the way back to ie8 on win7 so we should be good. 

Will update here in a few days.

**Comment by Ices-Eyes** [comment]
Hi guys...any news on this? Any hope to revert ie compatibility back? :)

**Comment by boemska-nik** [comment]
Hey @cj13579 @bozazec let's pick this up this week & get a babel built version of dist out

**Comment by cj13579** [comment]
@Ices-Eyes We've got a branch of the adapter with an [es5 build](https://github.com/Boemska/h54s/tree/97_problem_with_internet_explorer) that should help with this. I haven't tested this on IE8 anywhere yet but perhaps we can do some parallel testing of this.

@boemska-nik - Do we have an IE8 something that we can test this on?
